creative_mode = false
menu_last_game = voxelibre
maintab_LAST = local
dpi_change_notifier = 5
mainmenu_last_selected_world = 3
enable_damage = true
server_announce = false
screen_w = 1916
screen_h = 798
window_maximized = false
world_config_selected_mod = 1
mcl_enable_hunger = true
viewing_range = 180
mute_sound = false
free_move = false
fast_move = false
noclip = false
name = min2906
address = your-land.de
remote_port = 30000
